language: java
sudo: false
jdk:
  # java 7 not supported due to apache jena 3.x
  #- oraclejdk7
  # openjdk7 erroring with buffer overflow when test data is loaded
  #- openjdk7
  - oraclejdk8
addons:
  apt:
    packages:
      - libnetcdf-dev
install: mvn clean verify -Dioos-validate
notifications:
  flowdock: 7a05b97b59127301baa1b87fe93b3c41
#cache maven dependencies between builds
cache:
  directories:
  - $HOME/.m2
